var jspm, q, promises;
'use strict';
jspm = eval('require')(process.env['HOME'] + '/.jspm_global_packages/node_modules/jspm/api.js');
q = eval('require')(process.env['HOME'] + '/.jspm_global_packages/node_modules/q/q.js');
jspm.setPackagePath(process.env['HOME'] + '/.jspm_global_packages');
promises = [
  jspm.import('fs-extra@^1.0.0'),
  jspm.import('async-stacktrace'),
  jspm.import('wordwrap')
];
module.exports = q.all(promises).spread(function (module_fsextra100, ERR, wordwrap) {
  var import_file_existsstat, _;
  import_file_existsstat = module_fsextra100.stat;
  _ = function _(curr_path, cb) {
    var err, exists;
    import_file_existsstat(curr_path + '/.git', function (arguments, _$param0, _$param1) {
      err = _$param0;
      exists = _$param1;
      if (exists) {
        return cb(null, curr_path);
      }
      _(curr_path + '/..', cb);
    }.bind(this, arguments));
  };
  return _;
}).catch(function (err) {
  console.log(err);
});
/* Generated by Continuation.js v0.1.7 */