'use strict';

// file: shared/get_metadata

var jspm = eval('require')(process.env['HOME'] + '/.jspm_global_packages/node_modules/jspm/api.js');
var q = eval('require')(process.env['HOME'] + '/.jspm_global_packages/node_modules/q/q.js');
jspm.setPackagePath(process.env['HOME'] + '/.jspm_global_packages');
var promises = [
// load jspm
jspm.import('fs-extra@^1.0.0'), jspm.import('js-yaml@^3.7.0'),
// other
jspm.import('async-stacktrace'), jspm.import('wordwrap')];
module.exports = q.all(promises).spread(function (module_fsextra100, module_jsyaml370, ERR, wordwrap) {
    var import_read_filereadFile = module_fsextra100.readFile;
    var _ = function _(root_path) {
        return import_read_filereadFile(root_path + '/meta/data.yaml', 'utf8').then(function (metadata) {
            return module_jsyaml370.safeLoad(metadata);
        });
    };

    return _;
}).catch(function (err) {
    console.log(err);
});
/* Generated by Continuation.js v0.1.7 */