'use strict';

// file: shared/lambda_state_history

var jspm = eval('require')(process.env['HOME'] + '/.jspm_global_packages/node_modules/jspm/api.js');
var q = eval('require')(process.env['HOME'] + '/.jspm_global_packages/node_modules/q/q.js');
jspm.setPackagePath(process.env['HOME'] + '/.jspm_global_packages');
var promises = [
// other
jspm.import('async-stacktrace'), jspm.import('wordwrap')];
module.exports = q.all(promises).spread(function (ERR, wordwrap) {
    var _ = function _(project_path, cb) {
        cb();
    };

    module.exports = { add_new: add_new };
}).catch(function (err) {
    console.log(err);
});
/* Generated by Continuation.js v0.1.7 */