'use strict';

// file: shared/table_to_array

var jspm = eval('require')(process.env['HOME'] + '/.jspm_global_packages/node_modules/jspm/api.js');
var q = eval('require')(process.env['HOME'] + '/.jspm_global_packages/node_modules/q/q.js');
jspm.setPackagePath(process.env['HOME'] + '/.jspm_global_packages');
var promises = [
// load jspm
jspm.import('lodash/fp'),
// other
jspm.import('async-stacktrace'), jspm.import('wordwrap')];
module.exports = q.all(promises).spread(function (module_lodashfp, ERR, wordwrap) {
    var _ = function _(key_name, table) {
        return module_lodashfp.values(module_lodashfp.mapValues(table, function (val, key) {
            val[key_name] = key;
            return val;
        }));
    };

    return _;
}).catch(function (err) {
    console.log(err);
});
/* Generated by Continuation.js v0.1.7 */