var jspm, q, promises;
'use strict';
jspm = eval('require')(process.env['HOME'] + '/.jspm_global_packages/node_modules/jspm/api.js');
q = eval('require')(process.env['HOME'] + '/.jspm_global_packages/node_modules/q/q.js');
jspm.setPackagePath(process.env['HOME'] + '/.jspm_global_packages');
promises = [
  jspm.import('serialfs'),
  require('./_'),
  jspm.import('async-stacktrace'),
  jspm.import('wordwrap')
];
module.exports = q.all(promises).spread(function (module_serialfs, local_include__, ERR, wordwrap) {
  var _;
  _ = function _() {
    var cb, err, generated, expected;
    cb = function cb(err, generated, expected) {
      if (err) {
        console.log(wordwrap(20, 81)(err.stack.replace(/\\/g, '\\ ').replace(/^/gm, '.')).split('\n').forEach(function (stack_line) {
          console.log(stack_line.replace(/\\ /g, '\\').replace(/ at/g, '\nat').replace(/Error:/g, '\nError:'));
        }));
      }
      t.deepEqual(expected, generated);
      t.end();
    };
    local_include__(__dirname + '/../..', __dirname + '/before', 12345, function (arguments, _$param0) {
      err = _$param0;
      if (ERR(err, cb)) {
        return;
      }
      module_serialfs.obj(__dirname + '/before', {}, function (arguments, _$param1, _$param2) {
        err = _$param1;
        generated = _$param2;
        if (ERR(err, cb)) {
          return;
        }
        module_serialfs.obj(__dirname + '/expected_data', {}, function (arguments, _$param3, _$param4) {
          err = _$param3;
          expected = _$param4;
          if (ERR(err, cb)) {
            return;
          }
          cb(null, generated, expected);
        }.bind(this, arguments));
      }.bind(this, arguments));
    }.bind(this, arguments));
  };
  return _;
}).catch(function (err) {
  console.log(err);
});
/* Generated by Continuation.js v0.1.7 */