var jspm, q, promises;
'use strict';
jspm = eval('require')(process.env['HOME'] + '/.jspm_global_packages/node_modules/jspm/api.js');
q = eval('require')(process.env['HOME'] + '/.jspm_global_packages/node_modules/q/q.js');
jspm.setPackagePath(process.env['HOME'] + '/.jspm_global_packages');
promises = [
  jspm.import('fs-extra@^1.0.0'),
  jspm.import('serialfs'),
  require('./../create/_'),
  require('./../set_up/_'),
  require('./_'),
  jspm.import('async-stacktrace'),
  jspm.import('wordwrap')
];
module.exports = q.all(promises).spread(function (module_fsextra100, module_serialfs, local_include_create_, local_include_set_up_, local_include__, ERR, wordwrap) {
  var import_make_dirmkdirp, import_copy_pathcopy, _;
  import_make_dirmkdirp = module_fsextra100.mkdirp;
  import_copy_pathcopy = module_fsextra100.copy;
  _ = function _() {
    var cb, err, metadata, contents, generated, expected;
    cb = function cb(err, generated, expected) {
      if (err) {
        console.log(wordwrap(20, 81)(err.stack.replace(/\\/g, '\\ ').replace(/^/gm, '.')).split('\n').forEach(function (stack_line) {
          console.log(stack_line.replace(/\\ /g, '\\').replace(/ at/g, '\nat').replace(/Error:/g, '\nError:'));
        }));
      }
      t.deepEqual(generated, expected);
      t.end();
    };
    local_include_create_(__dirname + '/../..', __dirname, 'test_project', 2000, function (arguments, _$param0) {
      err = _$param0;
      if (ERR(err, cb)) {
        return;
      }
      import_make_dirmkdirp(__dirname + '/test_project/submodules');
      import_copy_pathcopy(__dirname + '/test_module_data', __dirname + '/test_project/submodules/test_module', function (arguments, _$param1) {
        err = _$param1;
        if (ERR(err, cb)) {
          return;
        }
        metadata = { project_name: 'test_project' };
        local_include_set_up_(__dirname + '/../..', __dirname + '/test_project', metadata, function (arguments, _$param2) {
          err = _$param2;
          if (ERR(err, cb)) {
            return;
          }
          local_include__(__dirname + '/test_project', function (arguments, _$param3) {
            err = _$param3;
            if (ERR(err, cb)) {
              return;
            }
            contents = {
              gen: {
                '.gitignore': true,
                dev: {
                  lambda_updatables: {
                    example_version: true,
                    'LICENCE.md': true
                  },
                  src: {
                    test_project: {
                      'test_project_test.es6': false,
                      'test_project_test.js': false,
                      'test_project.es6': false,
                      'test_project.js': false,
                      'metadata.yaml': false
                    }
                  }
                },
                stored: { 'lambda_state_history.yaml': true }
              }
            };
            generated = module_serialfs.obj(__dirname + '/test_project', contents, true, function (arguments, _$param4, _$param5) {
              err = _$param4;
              generated = _$param5;
              if (ERR(err, cb)) {
                return;
              }
              expected = module_serialfs.obj(__dirname + '/expected_data', contents, true, function (arguments, _$param6, _$param7) {
                err = _$param6;
                expected = _$param7;
                if (ERR(err, cb)) {
                  return;
                }
                cb(null, generated, expected);
              }.bind(this, arguments));
            }.bind(this, arguments));
          }.bind(this, arguments));
        }.bind(this, arguments));
      }.bind(this, arguments));
    }.bind(this, arguments));
  };
  return _;
}).catch(function (err) {
  console.log(err);
});
/* Generated by Continuation.js v0.1.7 */