'use strict';

// file: shared/jp

var jspm = eval('require')(process.env['HOME'] + '/.jspm_global_packages/node_modules/jspm/api.js');
var q = eval('require')(process.env['HOME'] + '/.jspm_global_packages/node_modules/q/q.js');
jspm.setPackagePath(process.env['HOME'] + '/.jspm_global_packages');
var promises = [
// load jspm
jspm.import('lodash/fp'),
// other
jspm.import('async-stacktrace'), jspm.import('wordwrap')];
module.exports = q.all(promises).spread(function (module_lodashfp, ERR, wordwrap) {
    var _ = function _() {
        for (var _len = arguments.length, promises = Array(_len), _key = 0; _key < _len; _key++) {
            promises[_key] = arguments[_key];
        }

        console.log(promises);
        return module_lodashfp.reduce(function (acc, promise) {
            return acc.then(promise);
        }, promises);
    };

    return _;
}).catch(function (err) {
    console.log(err);
});
/* Generated by Continuation.js v0.1.7 */