'use strict';

// file: shared/move_if_exists

var jspm = eval('require')(process.env['HOME'] + '/.jspm_global_packages/node_modules/jspm/api.js');
var q = eval('require')(process.env['HOME'] + '/.jspm_global_packages/node_modules/q/q.js');
jspm.setPackagePath(process.env['HOME'] + '/.jspm_global_packages');
var promises = [
// load jspm
jspm.import('fs-extra@^1.0.0'),
// other
jspm.import('async-stacktrace'), jspm.import('wordwrap')];
module.exports = q.all(promises).spread(function (module_fsextra100, ERR, wordwrap) {
    var import_move_pathmove = module_fsextra100.move;
    var _ = function _(from, to, cb) {
        var handle_response = function handle_response() {
            cb();
        };

        import_move_pathmove(from, to, handle_response);
    };

    return _;
}).catch(function (err) {
    console.log(err);
});
/* Generated by Continuation.js v0.1.7 */