'use strict';

// file: shared/update_updatables

var jspm = eval('require')(process.env['HOME'] + '/.jspm_global_packages/node_modules/jspm/api.js');
var q = eval('require')(process.env['HOME'] + '/.jspm_global_packages/node_modules/q/q.js');
jspm.setPackagePath(process.env['HOME'] + '/.jspm_global_packages');
var promises = [
// other
jspm.import('async-stacktrace'), jspm.import('wordwrap')];
module.exports = q.all(promises).spread(function (ERR, wordwrap) {
    var _ = module.exports = function (root_path, project_path, cb) {
        console.log('updated updatables (didnt actually do anything)');
        cb();
    };
}).catch(function (err) {
    console.log(err);
});
/* Generated by Continuation.js v0.1.7 */