'use strict';

// file: set_up/tools

var jspm = eval('require')(process.env['HOME'] + '/.jspm_global_packages/node_modules/jspm/api.js');
var q = eval('require')(process.env['HOME'] + '/.jspm_global_packages/node_modules/q/q.js');
jspm.setPackagePath(process.env['HOME'] + '/.jspm_global_packages');
var promises = [
// load jspm
jspm.import('remove_path'), jspm.import('fs-extra@^1.0.0'),
// load local
require('./../shared/jp'), require('./../shared/copy_if_exists'),
// other
jspm.import('async-stacktrace'), jspm.import('wordwrap')];
module.exports = q.all(promises).spread(function (module_remove_path, module_fsextra100, local_include_sharedjp, local_include_sharedcopy_if_exists, ERR, wordwrap) {
    var import_make_dirmkdirp = module_fsextra100.mkdirp;
    var _ = function _(mu_src_path, root, metadata, cb) {
        var gen_path = root + '/generated_local/tools';
        return local_include_sharedjp(module_remove_path(gen_path), import_make_dirmkdirp(gen_path), local_include_sharedcopy_if_exists(root + '/tools', gen_path), import_make_dirmkdirp(root + '/generated/tools'));
    };

    return _;
}).catch(function (err) {
    console.log(err);
});
/* Generated by Continuation.js v0.1.7 */