'use strict';

var fs = require('fs-extra');
var tools = require('./tools');

var out = function out(a, b) {
    console.log(a);
    console.log(b);
};

module.exports = out;

out(1, 2);
/* Generated by Continuation.js v0.1.7 */