'use strict';

module.exports = {
    build_dev: function build_dev(cb) {
        console.log('working2');
        return 'abcd';
    } };
console.log(module.exports);
/* Generated by Continuation.js v0.1.7 */