'use strict';

// file: unbrace/clear_line_end

var jspm = eval('require')(process.env['HOME'] + '/.jspm_global_packages/node_modules/jspm/api.js');
var q = eval('require')(process.env['HOME'] + '/.jspm_global_packages/node_modules/q/q.js');
jspm.setPackagePath(process.env['HOME'] + '/.jspm_global_packages');
var promises = [
// load jspm
jspm.import('lodash/fp'),
// other
jspm.import('async-stacktrace'), jspm.import('wordwrap')];
module.exports = q.all(promises).spread(function (module_lodashfp, ERR, wordwrap) {
    var _ = function _(symbols_to_remove, i) {
        if (i.err) return i;
        return module_lodashfp.reduce(symbols_to_remove, function (acc, symbol) {
            if (acc.err) {
                return acc;
            }
            var str = acc.line.trim();
            if (symbol !== str.slice(-1)) {
                return { err: true, line: str };
            }
            return { err: false, line: str.slice(0, -1) };
        }, i);
    };

    return _;
}).catch(function (err) {
    console.log(err);
});
/* Generated by Continuation.js v0.1.7 */