'use strict';

// file: unbrace/clear_line_ends

var jspm = eval('require')(process.env['HOME'] + '/.jspm_global_packages/node_modules/jspm/api.js');
var q = eval('require')(process.env['HOME'] + '/.jspm_global_packages/node_modules/q/q.js');
jspm.setPackagePath(process.env['HOME'] + '/.jspm_global_packages');
var promises = [
// load local
require('./clear_line_end'),
// other
jspm.import('async-stacktrace'), jspm.import('wordwrap')];
module.exports = q.all(promises).spread(function (local_include_clear_line_end, ERR, wordwrap) {
    var _ = function _(i) {
        var res = local_include_clear_line_end(i.multiline_symbols.closes, local_include_clear_line_end(i.multiline_symbols.opened, { err: false, line: i.line }));
        if (res.err) return { line: i.line, multiline_symbols: [] };
        i.line = res.line;
        return i;
    };

    return _;
}).catch(function (err) {
    console.log(err);
});
/* Generated by Continuation.js v0.1.7 */