'use strict';

// file: diff/dump_table

var jspm = eval('require')(process.env['HOME'] + '/.jspm_global_packages/node_modules/jspm/api.js');
var q = eval('require')(process.env['HOME'] + '/.jspm_global_packages/node_modules/q/q.js');
jspm.setPackagePath(process.env['HOME'] + '/.jspm_global_packages');
var promises = [
// load jspm
jspm.import('lodash/fp'),
// other
jspm.import('async-stacktrace'), jspm.import('wordwrap')];
module.exports = q.all(promises).spread(function (module_lodashfp, ERR, wordwrap) {
    var _ = function _(i, dump) {
        var path = i.path;
        var table = i.obj;
        var current_diff_i = null;
        if (i.current_diff) current_diff_i = i.current_diff.index;
        i.current_diff = null;
        var ret = module_lodashfp.values(module_lodashfp.mapValues(i.obj, function (val, key) {
            i.path = module_lodashfp.clone(path);
            i.path.push(key);
            i.obj = table[key];
            var item_str = dump(i);
            return key + ': ' + item_str.replace(/\n/g, '\n  ');
        })).join('\n');
        return ret;
    };

    return _;
}).catch(function (err) {
    console.log(err);
});
/* Generated by Continuation.js v0.1.7 */