#!/bin/bash
cd ~/.jspm_global_packages
~/.jspm_global_packages/node_modules/.bin/jspm install async-stacktrace@0.0.2=npm:async-stacktrace@0.0.2
~/.jspm_global_packages/node_modules/.bin/jspm install babel-preset-es2015@^6.18.0=npm:babel-preset-es2015@^6.18.0
~/.jspm_global_packages/node_modules/.bin/jspm install continuation@^0.1.7=npm:continuation@^0.1.7
~/.jspm_global_packages/node_modules/.bin/jspm install fs-extra@^1.0.0=npm:fs-extra@^1.0.0
~/.jspm_global_packages/node_modules/.bin/jspm install commander=npm:commander
~/.jspm_global_packages/node_modules/.bin/jspm install git-archive@^0.1.4=npm:git-archive@^0.1.4
~/.jspm_global_packages/node_modules/.bin/jspm install gulp@^3.9.1=npm:gulp@^3.9.1
~/.jspm_global_packages/node_modules/.bin/jspm install gulp-babel@^6.1.2=npm:gulp-babel@^6.1.2
~/.jspm_global_packages/node_modules/.bin/jspm install gulp-continuation@^1.1.1=npm:gulp-continuation@^1.1.1
~/.jspm_global_packages/node_modules/.bin/jspm install gulp-debug@^2.1.2=npm:gulp-debug@^2.1.2
~/.jspm_global_packages/node_modules/.bin/jspm install gulp-footer@^1.0.5=npm:gulp-footer@^1.0.5
~/.jspm_global_packages/node_modules/.bin/jspm install gulp-header@^1.8.8=npm:gulp-header@^1.8.8
~/.jspm_global_packages/node_modules/.bin/jspm install gulp-include@^2.3.1=npm:gulp-include@^2.3.1
~/.jspm_global_packages/node_modules/.bin/jspm install gulp-inject-string@^1.1.0=npm:gulp-inject-string@^1.1.0
~/.jspm_global_packages/node_modules/.bin/jspm install gulp-insert@^0.5.0=npm:gulp-insert@^0.5.0
~/.jspm_global_packages/node_modules/.bin/jspm install gulp-insert-lines@0.0.4=npm:gulp-insert-lines@0.0.4
~/.jspm_global_packages/node_modules/.bin/jspm install gulp-replace@^0.5.4=npm:gulp-replace@^0.5.4
~/.jspm_global_packages/node_modules/.bin/jspm install gulp-sequence@^0.4.6=npm:gulp-sequence@^0.4.6
~/.jspm_global_packages/node_modules/.bin/jspm install gulp-yarn@0.0.5=npm:gulp-yarn@0.0.5
~/.jspm_global_packages/node_modules/.bin/jspm install js-yaml@^3.7.0=npm:js-yaml@^3.7.0
~/.jspm_global_packages/node_modules/.bin/jspm install object-merge-override@^0.1.0=npm:object-merge-override@^0.1.0
~/.jspm_global_packages/node_modules/.bin/jspm install serialfs@0.0.21=npm:serialfs@0.0.21
~/.jspm_global_packages/node_modules/.bin/jspm install shebang-loader@0.0.1=npm:shebang-loader@0.0.1
~/.jspm_global_packages/node_modules/.bin/jspm install string-template@^1.0.0=npm:string-template@^1.0.0
~/.jspm_global_packages/node_modules/.bin/jspm install tap-difflet@^0.7.0=npm:tap-difflet@^0.7.0
~/.jspm_global_packages/node_modules/.bin/jspm install tape@^4.6.3=npm:tape@^4.6.3
~/.jspm_global_packages/node_modules/.bin/jspm install tar-fs@^1.15.0=npm:tar-fs@^1.15.0
~/.jspm_global_packages/node_modules/.bin/jspm install tarball-extract@0.0.3=npm:tarball-extract@0.0.3
~/.jspm_global_packages/node_modules/.bin/jspm install try-thread-sleep@^1.0.0=npm:try-thread-sleep@^1.0.0
~/.jspm_global_packages/node_modules/.bin/jspm install user-home@^2.0.0=npm:user-home@^2.0.0
~/.jspm_global_packages/node_modules/.bin/jspm install vargs-callback@^0.2.4=npm:vargs-callback@^0.2.4
~/.jspm_global_packages/node_modules/.bin/jspm install vinyl-transform@^1.0.0=npm:vinyl-transform@^1.0.0
~/.jspm_global_packages/node_modules/.bin/jspm install webpack-node-externals@^1.5.4=npm:webpack-node-externals@^1.5.4
~/.jspm_global_packages/node_modules/.bin/jspm install webpack-stream@^3.2.0=npm:webpack-stream@^3.2.0
~/.jspm_global_packages/node_modules/.bin/jspm install word-wrap@^1.1.0=npm:word-wrap@^1.1.0
~/.jspm_global_packages/node_modules/.bin/jspm install npm:async-stacktrace
~/.jspm_global_packages/node_modules/.bin/jspm install npm:word-wrap
~/.jspm_global_packages/node_modules/.bin/jspm install npm:gulp-strip-comments
~/.jspm_global_packages/node_modules/.bin/jspm install npm:ramda
~/.jspm_global_packages/node_modules/.bin/jspm install npm:vargs-callback
