var jspm, q, promises;
'use strict';
jspm = eval('require')(process.env['HOME'] + '/.jspm_global_packages/node_modules/jspm/api.js');
q = eval('require')(process.env['HOME'] + '/.jspm_global_packages/node_modules/q/q.js');
jspm.setPackagePath(process.env['HOME'] + '/.jspm_global_packages');
promises = [
  require('./_test'),
  jspm.import('async-stacktrace'),
  jspm.import('wordwrap')
];
module.exports = q.all(promises).spread(function (local_include__test, ERR, wordwrap) {
  var _;
  _ = function _(commander) {
    var success_message;
    success_message = 'tests complete';
    commander.command('test').description('run all tests').action(function () {
      var err;
      local_include__test(function (arguments, _$param0) {
        err = _$param0;
        if (ERR(err, cb)) {
          return;
        }
        console.log(success_message);
      }.bind(this, arguments));
    });
  };
  return _;
}).catch(function (err) {
  console.log(err);
});
/* Generated by Continuation.js v0.1.7 */