'use strict';

// file: lambda_pattern/_test

var jspm = eval('require')(process.env['HOME'] + '/.jspm_global_packages/node_modules/jspm/api.js');
var q = eval('require')(process.env['HOME'] + '/.jspm_global_packages/node_modules/q/q.js');
jspm.setPackagePath(process.env['HOME'] + '/.jspm_global_packages');
var promises = [
// load jspm
jspm.import('bluebird'), jspm.import('marked'), jspm.import('marked-terminal'),
// load local
require('./shared/concat_promises'), require('./set_up/_test'),
// other
jspm.import('async-stacktrace'), jspm.import('wordwrap')];
module.exports = q.all(promises).spread(function (module_bluebird, module_marked, module_markedterminal, local_include_sharedconcat_promises, local_include_set_up_test, ERR, wordwrap) {
    var _ = function _() {
        module_bluebird.config({ warnings: false, longStackTraces: false });
        module_marked.setOptions({ renderer: new module_markedterminal() });

        local_include_sharedconcat_promises('test results:', [local_include_set_up_test]).then(function (i) {
            console.log(i);
        }).catch(function (i) {
            console.log(i);
        });
    };

    return _;
}).catch(function (err) {
    console.log(err);
});
/* Generated by Continuation.js v0.1.7 */