var jspm, q, promises;
'use strict';
jspm = eval('require')(process.env['HOME'] + '/.jspm_global_packages/node_modules/jspm/api.js');
q = eval('require')(process.env['HOME'] + '/.jspm_global_packages/node_modules/q/q.js');
jspm.setPackagePath(process.env['HOME'] + '/.jspm_global_packages');
promises = [
  jspm.import('fs-extra@^1.0.0'),
  require('./../shared/move_if_exists'),
  require('./move_if_exists'),
  jspm.import('async-stacktrace'),
  jspm.import('wordwrap')
];
module.exports = q.all(promises).spread(function (module_fsextra100, local_include_sharedmove_if_exists, local_include_move_if_exists, ERR, wordwrap) {
  var _;
  _ = function _(root_path, updatables_version, cb) {
    var move_if_exists, err;
    move_if_exists = local_include_sharedmove_if_exists;
    module_fsextra100.mkdirp(root_path + '/generated/tools/stored', function (arguments, _$param0) {
      err = _$param0;
      if (ERR(err, cb)) {
        return;
      }
      local_include_move_if_exists(root_path + '/generated/tools/_.js', root_path + '/generated/tools/stored/' + updatables_version + '.js', function (arguments, _$param1) {
        err = _$param1;
        if (ERR(err, cb)) {
          return;
        }
        module_fsextra100.move(root_path + '/generated_local/tools/__built.js', root_path + '/generated/tools/_.js', cb);
      }.bind(this, arguments));
    }.bind(this, arguments));
  };
  return _;
}).catch(function (err) {
  console.log(err);
});
/* Generated by Continuation.js v0.1.7 */