'use strict';

// file: unbrace/_test

var jspm = eval('require')(process.env['HOME'] + '/.jspm_global_packages/node_modules/jspm/api.js');
var q = eval('require')(process.env['HOME'] + '/.jspm_global_packages/node_modules/q/q.js');
jspm.setPackagePath(process.env['HOME'] + '/.jspm_global_packages');
var promises = [
// load jspm
jspm.import('bluebird'),
// load local
require('./before.txt'), require('./unbrace'),
// other
jspm.import('async-stacktrace'), jspm.import('wordwrap')];
module.exports = q.all(promises).spread(function (module_bluebird, local_include_beforetxt, local_include_unbrace, ERR, wordwrap) {
    var _ = function _() {
        var before = local_include_beforetxt;
        local_include_unbrace(before);
        return module_bluebird.resolve();
    };

    return _;
}).catch(function (err) {
    console.log(err);
});
/* Generated by Continuation.js v0.1.7 */